services:
  db:
    image: postgres:15-alpine
    container_name: applicant_benchmark_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: applicant_db
    ports:
      - "5432:5432"
    volumes:
      # Use ./ to tell Docker the file is in the current directory
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      # Persistent data (this stays as is)
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: